export const countries = [
  {
    name: 'Costa Rica',
    currency: 'crc',
    iso_code: 'CR',
    symbol: '₡',
    code: '+506',
  },
  {
    name: 'España',
    currency: 'eur',
    iso_code: 'ES',
    symbol: '€',
    code: '+34',
  },
  {
    name: 'Panamá',
    currency: 'pab',
    iso_code: 'PA',
    symbol: '$',
    code: '+507',
  },
  {
    name: 'Colombia',
    currency: 'cop',
    iso_code: 'CO',
    symbol: '$',
    code: '+57',
  },
  {
    name: 'México',
    currency: 'mxn',
    iso_code: 'MX',
    symbol: '$',
    code: '+52',
  },
  {
    name: 'Guatemala',
    currency: 'gtq',
    iso_code: 'GT',
    symbol: 'Q',
    code: '+502',
  },
  {
    name: 'El Salvador',
    currency: 'usd',
    iso_code: 'SV',
    symbol: '$',
    code: '+503',
  },
  {
    name: 'Honduras',
    currency: 'hnl',
    iso_code: 'HN',
    symbol: 'L',
    code: '+504',
  },
  {
    name: 'Nicaragua',
    currency: 'nio',
    iso_code: 'NI',
    symbol: 'C$',
    code: '+505',
  },
  {
    name: 'República Dominicana',
    currency: 'dop',
    iso_code: 'DO',
    symbol: 'RD$',
    code: '+1',
  },
  {
    name: 'Puerto Rico',
    currency: 'usd',
    iso_code: 'PR',
    symbol: '$',
    code: '+1',
  },
  {
    name: 'Estados Unidos',
    currency: 'usd',
    iso_code: 'US',
    symbol: '$',
    code: '+1',
  },
  {
    name: 'Argentina',
    currency: 'ars',
    iso_code: 'AR',
    symbol: '$',
    code: '+54',
  },
  {
    name: 'Bolivia',
    currency: 'bob',
    iso_code: 'BO',
    symbol: '$b',
    code: '+591',
  },
  {
    name: 'Chile',
    currency: 'clp',
    iso_code: 'CL',
    symbol: '$',
    code: '+56',
  },
  {
    name: 'Ecuador',
    currency: 'usd',
    iso_code: 'EC',
    symbol: '$',
    code: '+593',
  },
  {
    name: 'Paraguay',
    currency: 'pyg',
    iso_code: 'PY',
    symbol: '₲',
    code: '+595',
  },
  {
    name: 'Perú',
    currency: 'pen',
    iso_code: 'PE',
    symbol: 'S/',
    code: '+51',
  },
  {
    name: 'Uruguay',
    currency: 'uyu',
    iso_code: 'UY',
    symbol: '$',
    code: '+598',
  },
  {
    name: 'Venezuela',
    currency: 'usd',
    iso_code: 'VE',
    symbol: '$',
    code: '+58',
  },
  {
    name: 'Brasil',
    currency: 'brl',
    iso_code: 'BR',
    symbol: 'R$',
    code: '+55',
  },
  {
    name: 'Canadá',
    currency: 'cad',
    iso_code: 'CA',
    symbol: '$',
    code: '+1',
  },
];
