export enum TypeFileEnum {
  AUDIO_POPUPS = 'AUDIO_POPUPS',
  AUDIO_REWARDS_CLAIMED = 'AUDIO_REWARDS_CLAIMED',
  AUDIO_REWARDS_DISQUALIFIED = 'AUDIO_REWARDS_DISQUALIFIED',
  AUDIO_REWARDS = 'AUDIO_REWARDS',
}
