name: Deploy Backend Norita APP

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.2.0

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Instalar dependencias y compilar
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
          
      - name: Comprimir archivos
        run: tar -czf deploy.tar.gz dist package.json pnpm-lock.yaml 

      - name: Enviar archivos al servidor por SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "deploy.tar.gz"
          target: "/tmp"

      - name: Staging, Migraciones y PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            # =========================================================
            # 0. CARGAR RUTAS DEL SISTEMA (PATH)
            # =========================================================
            export PATH="/home/ubuntu/.nvm/versions/node/v24.11.0/bin:$PATH"
            
            # =========================================================
            # 1. FORZAR LA CARGA DE VARIABLES DE ENTORNO
            # =========================================================
            set -a
            source /etc/environment
            set +a
            
            # 2. Crear staging temporal y extraer
            mkdir -p /tmp/norita_staging
            tar -xzf /tmp/deploy.tar.gz -C /tmp/norita_staging
            
            # 3. Instalar SOLO dependencias de producción
            cd /tmp/norita_staging
            pnpm install --prod --frozen-lockfile
          
            # 4. EJECUTAR MIGRACIONES TYPEORM EN PRODUCCIÓN
            pnpm run migrations:run:prod
            
            # =========================================================
            # 5. PASAR A PRODUCCIÓN
            # =========================================================
            rsync -a --delete --exclude='public' --exclude='.git' /tmp/norita_staging/ /home/ubuntu/norita_back/
            
            # 6. Recargar PM2
            cd /home/ubuntu/norita_back
            pm2 reload norita_back --update-env || pm2 start dist/main.js --name "norita_back"
            
            # 7. Limpiar
            rm -rf /tmp/norita_staging
            rm /tmp/deploy.tar.gz
